[package]
name = "raytracer"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
rayon = "1.7"
fastrand = "2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
